name: CD

on:
  push:
    branches: master

jobs:
  test:
    uses: YuGiOhBot3000/submission/.github/workflows/unit.yml@master
  deploy:
    needs: test
    uses: YuGiOhBot3000/submission/.github/workflows/deploy.yml@master
