name: Deployment

on:
  workflow_call:
    inputs:
      node-version:
        default: "16"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build site
        run: yarn build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
