name: Unit Tests

on:
  workflow_call:
    inputs:
      node-version:
        default: "16"
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
